Controllers films users
Primorets/java-filmorate pull request #1
Opened 2022-11-22 19:10 UTC by Primorets

2022-11-23 04:14 UTC, sergeymamonov requested changes

2022-11-23 04:14 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/rest/FilmControllerTest.java
> +        Film film = new Film(1, "film1", simbols,
Обратите внимание, в каждом тесте создается фильм. Можно же сделать метод, который будет выполняться перед каждым тестом **(@BeforeEach)** и в этом методе создать корректный фильм. А уже в тесте заменять в этом объекте одно из полей на невалидное.

2022-11-23 04:14 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/rest/FilmControllerTest.java
> +        FilmsAndUsersValidationException exception = assertThrows(FilmsAndUsersValidationException.class,
То же самое, только через лямбду
FilmsAndUsersValidationException exception = assertThrows(FilmsAndUsersValidationException.class, () -> filmController.validate(film));

2022-11-23 04:14 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/rest/FilmControllerTest.java
> +        assertEquals("invalid releaseDate", exception.getMessage());
По этому тексту непонятно будет, что нужно сделать. То ли формат даты невалиден, то ли слишком ранняя дата и так далее.

2022-11-23 04:14 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/rest/FilmController.java
> +    Map<Integer, Film> allFilms = new HashMap();
HashMap параметризованный класс, то есть пропущены <>.
Плюс пропущены модификаторы доступа у этого поля и строчкой ниже. Это же поля класса, значит лучше указать модификатор доступа.

2022-11-23 04:14 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/rest/FilmController.java
> +    Collection<Film> getFilms(Film film) {
У методов намеренно не указан модификатор доступа?

2022-11-23 04:14 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/rest/UserController.java
> +    Collection<User> getAllUsers() {
Лучше возвращать не Collection, а List. Collection - слишком общий интерфейс. То есть может вернуться как List, так и Set.

2022-11-28 17:58 UTC, Primorets commented on src/test/java/ru/yandex/practicum/filmorate/rest/FilmControllerTest.java
> +        String simbols = "The film is set in Middle-earth – a land where such “goodly” races as hobbits, elves," +
Поправил. Спасибо.

2022-11-28 18:02 UTC, Primorets commented on src/test/java/ru/yandex/practicum/filmorate/rest/FilmControllerTest.java
> +        Film film = new Film(1, "film1", simbols,
Добавил метод.

2022-11-28 18:03 UTC, Primorets commented on src/test/java/ru/yandex/practicum/filmorate/rest/FilmControllerTest.java
> +        FilmsAndUsersValidationException exception = assertThrows(FilmsAndUsersValidationException.class,
Поправил.

2022-11-28 18:05 UTC, Primorets commented on src/test/java/ru/yandex/practicum/filmorate/rest/FilmControllerTest.java
> +        assertEquals("invalid releaseDate", exception.getMessage());
Добавил уточнения.

2022-11-28 18:06 UTC, Primorets commented on src/main/java/ru/yandex/practicum/filmorate/rest/FilmController.java
> +    Map<Integer, Film> allFilms = new HashMap();
Добавил.

2022-11-28 18:11 UTC, Primorets commented on src/main/java/ru/yandex/practicum/filmorate/rest/FilmController.java
> +    Collection<Film> getFilms(Film film) {
Не намеренно, упустил. Добавил.

2022-11-29 03:34 UTC, sergeymamonov approved these changes

2022-11-29 03:34 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/rest/FilmController.java
> +        if (film.getDescription().length() > 200) {
Лучше стараться убирать числа из кода в константы, переменны и так далее. Ниже дата, ее тоже в константу.

2022-12-05 17:23 UTC, Primorets commented on src/main/java/ru/yandex/practicum/filmorate/rest/FilmController.java
> +        if (film.getDescription().length() > 200) {
Убрал. Спасибо.

2022-12-05 17:26 UTC, merged