Add friends likes
Primorets/java-filmorate pull request #2
Opened 2022-12-25 18:38 UTC by Primorets

2022-12-26 09:59 UTC, sergeymamonov requested changes

2022-12-26 09:59 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/rest/FilmController.java
>          validateFilm(film);
Вся бизнес логика: валидация и пр. должна быть в сервисе.

2022-12-26 09:59 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        Set<Integer> firstUserFriends = new HashSet<>(get(userId).getFriendsId()); //get(userId).getFriendsId();
Закомментированного кода быть не должно.

2022-12-26 09:59 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        List<User> usersList = new ArrayList<>(allUsers.values());
Не обязательно создавать лишнюю переменную
return new ArrayList<>(allUsers.values());

2022-12-26 09:59 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    private HashMap<Integer, User> allUsers = new HashMap<>();
Определять нужно на уровне интерфейсов, то есть private Map<Integer, User> allUsers. В фильмах аналогично.

2022-12-26 17:18 UTC, Primorets commented on src/main/java/ru/yandex/practicum/filmorate/rest/FilmController.java
>          validateFilm(film);
Поправил. Спасибо.

2022-12-26 18:01 UTC, Primorets commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        Set<Integer> firstUserFriends = new HashSet<>(get(userId).getFriendsId()); //get(userId).getFriendsId();
Поправил.

2022-12-26 18:01 UTC, Primorets commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        List<User> usersList = new ArrayList<>(allUsers.values());
Поправил.

2022-12-26 18:01 UTC, Primorets commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    private HashMap<Integer, User> allUsers = new HashMap<>();
Поправил.

2022-12-27 14:36 UTC, sergeymamonov approved these changes

2022-12-27 17:22 UTC, merged