Add database
Primorets/java-filmorate pull request #3
Opened 2023-02-11 12:28 UTC by Primorets

2023-02-12 05:29 UTC, sergeymamonov requested changes

2023-02-12 05:29 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/DbFilmStorage.java
> +    private Genre MapToGenre(ResultSet resultSet, int rowNum) throws SQLException {
Маппинг лучше выделить в отдельный класс.

2023-02-12 19:52 UTC, Primorets commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/DbFilmStorage.java
> +    private Genre MapToGenre(ResultSet resultSet, int rowNum) throws SQLException {
Маппинги выделены в отдельные классы. Спасибо.

2023-02-13 16:35 UTC, sergeymamonov approved these changes

2023-02-13 16:35 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/mapping/MapRowForGenres.java
> +    public Genre mapRow(ResultSet resultSet, int rowNum) throws SQLException {
Зачем здесь параметр rowNum? В других мапперах аналогично.

2023-02-13 16:35 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/mapping/MapRowForFilm.java
> +        } catch (NotFoundException notFoundException) {
А что может бросить это исключение? Маппер конвертирует один объект в другой. То есть можно проверить на нулл что приходит. Но ошибку здесь кидать не нужно. Валидировать данные нужно в сервисе.

2023-03-04 08:26 UTC, merged